default: &default
  host: weatherstation
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['DATABASE_USR'] %>
  password: <%= ENV['DATABASE_PWD'] %>

development:
  <<: *default
  database: kitchen_development

test:
  <<: *default
  database: kitchen_test

production:
  <<: *default
  database: kitchen_production

