default: &default
  host: weatherstation
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: manuel
  password: qwdghf23qw

development:
  <<: *default
  database: kitchen_development

test:
  <<: *default
  database: kitchen_test

production:
  <<: *default
  database: kitchen_production

